sonar.projectKey=Jean_Cuzcano_t1
sonar.sources=consumer,producer,domain,infrastructure
sonar.tests=tests

sonar.exclusions=.venv/**,**/__pycache__/**,**/.pytest_cache/**,coverage.xml
sonar.test.inclusions=tests/**/*.py
sonar.python.coverage.reportPaths=coverage.xml

sonar.coverage.exclusions=consumer/consumer_rabbit.py,producer/producer_rabbit.py,infrastructure/rabbitmq_connection.py,**/__init__.py
sonar.cpd.exclusions=consumer/consumer_rabbit.py,producer/producer_rabbit.py

sonar.host.url=https://sonarqube.ingsoftware.lat/
sonar.token=${SONAR_TOKEN}